# Custom Language File for Launcher Customizer

[ejs.app]
title = "Exode Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR EXODE"
welcomeDescription = "Exode est un serveur Minecraft Roleplay de type Médiéval - Fantasy - Isekai."
welcomeDescCTA = "Vous êtes à quelques clics de lancer Exode."
